- name: Get join-token for worker nodes
  set_fact:
    join_token_worker: "{{ hostvars['manager-18-04'].swarm_info.swarm_facts.JoinTokens.Worker }}"

- name: Join Swarm
  community.docker.docker_swarm:
    state: join
    advertise_addr: "{{  inventory_hostname  }}"
    remote_addrs: [ 'manager-18-04:2377' ]
    join_token: "{{ join_token_worker }}"