
  - name: Install Dependancies
    apt:
      pkg:
        - apt-transport-https 
        - ca-certificates 
        - curl 
        - gnupg 
        - lsb-release
        - python3
        - python3-pip
      state: latest
      update_cache: true
  
  - name: Configure GPG
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Install Docker
    apt:
      pkg: 
      -  docker-ce
      -  docker-ce-cli
      -  containerd.io
      update_cache: true

  - name: Install Docker SDK
    pip:
      name: docker

  - name: Install Jsondiff
    pip:
      name: jsondiff

  - name: Add User To Docker
    user:
      name: tommycalvin
      groups: docker
      append: true